### ISSUE TITLE
OSNAP cruise needs

### ISSUE THREAD

**Issue by mvkovatch3** [cchdo/ctdcal#49]
### Functions:
- [x] read Sea-Bird .cnv files
- [x] read non-ODF autosal data files
- [x] WHOI fit methodology (T/C likely same, O likely different)
- [ ] Aandera optode routines (we only have Rinko at present)

### Questions:
- [x] data output format? (likely not Exchange)
- [ ] absolute precision? or what other metric for good/bad flagging?

### Miscellaneous:
- [ ] SBE Processing .dsa files (real-time plots and layouts)
- [ ] examples of bad data (biofouling, ruptured membrane, etc.)

**Comment by Klankers** [comment]
The cruise has concluded and the data have been accepted by the science party.

- Aanderaa optodes were not used on the cruise.
- .dsa files were created in accordance with P02 reference (1 physiochemical, 1 bio, TS, oxygen types).
- No unmanageable biofouling events. Documented in cruise report.

Copying the quesiton of good/bad flagging to #55 .
