### ISSUE TITLE
Codecov occasional failing

### ISSUE THREAD

**Issue by mvkovatch3** [cchdo/ctdcal#53]
Known bug, see https://github.com/codecov/codecov-action/issues/598

Current solution seems to be re-running failing test(s) manually.

**Comment by DocOtak** [comment]
Maybe change https://github.com/cchdo/ctdcal/blob/d560c557df23ef7ba0a7812075e9d7591c3b56f8/.github/workflows/run-tests.yml#L43 to ``false`` 

That's what is in [xarray](https://github.com/pydata/xarray/blob/cc7e09a3507fa342b3790b5c109e700fa12f0b17/.github/workflows/ci.yaml#L134-L141) at least.

**Comment by mvkovatch3** [comment]
Fixed with 4e496e16d85080a22b0226864bfb0b8caabd631e
