### ISSUE TITLE
Assess TODO markers

### ISSUE THREAD

**Issue by Klankers** [cchdo/ctdcal#56]
CTDCAL has numerous TODO markers of unknown age, origin, context, or intent.

1. Run through all the modules, scripts, and tools and consolidate all of the TODOs into a list.
2. From there, determine what should be done (via discussion) about each TODO. Are they immediate changes? Do we need new issues? Are they redundant or irrelevant?
3. Delete all the TODOs in the code.

**Comment by DocOtak** [comment]
Also interesting is something like https://github.com/alstr/todo-to-issue-action

**Comment by Klankers** [comment]
See the following branches also:

 - P02 
 - Xarray 
 - load_all_nc_files 
 - gt2022

**Comment by Klankers** [comment]
> Also interesting is something like https://github.com/alstr/todo-to-issue-action

Isn't currently possible with the permissions on the Github tokens (can't enable "read and write" permissions for workflows). Possibly in the future?

**Comment by asmith75218** [comment]
Actions have either been added to open issues or resolved. Most TODO markers removed from code. A few remain in unused modules and older branches. I think one more discussion and we can resolve and close this issue.

**Comment by Klankers** [comment]
Only other mentions of TODOs are in:
* file_comparison.py - something we'll want functionality for in a future milestone but not in this 2017 style
* bokeh_btl... - a RINKO visualizer from 2020, with functionality that can be reintegrated into our QC tool
* bokeh_ctd... - a predacessor to the current QC tool

After discussing and assessing these, we decided they weren't files we need to keep and, for simplicity, can be deleted.

**Comment by asmith75218** [comment]
Comments resolved, unneeded files removed.
