### ISSUE TITLE
Assess AUX sensor processors

### ISSUE THREAD

**Issue by Klankers** [cchdo/ctdcal#57]
GO-SHIP doesn't use xmiss, fluor, or turb sensors outside of their engineering units, often reported as just a voltage.

Confirm that the functions present in CTDCAL all still work as intended and they are adequately documented.

- [x] Transmissometer
- [x] Fluorometer
- [x] Turbidity sensor

**Comment by Klankers** [comment]
Add sensors to `convert` and confirm that they can be converted. Coefficients are almost always stored in a .PDF, so the user would need to supply them (provide "defaults"?)

 - P02: Sensor ID # 13 - CTDFLUOR (FLF-Fluorometer)
 - OSNAP32: ECO-FLNTU addition to config
 - OSNAP32: TURB/FLUOR to science units

**Comment by asx-** [comment]
You could do optical recognition, there must be libraries for that in
python, but you’d still want a manual check by the analyst.

**Comment by Klankers** [comment]
```
def seapoint_fluor(volts, coefs, decimals=6):
   """
   _check_coefs(coefs, ["GainSetting", "Offset"])
   # TODO: actual calibration/conversion/something?
   # TODO: move this to different module? edge case since it's the only Seapoint
```
   
More context. Support for seapoint fluorometer as well.

**Comment by Klankers** [comment]
Fluor, Xmiss equations unchanged in latest SBE documents.
Added FLNTU functions (turb, CDOM chl sensors using gain function)
