### ISSUE TITLE
Consolidate manual flags

### ISSUE THREAD

**Issue by Klankers** [cchdo/ctdcal#60]
Consolidate the manual flags. I.e., the flags for bottles we _know_ are not a WOCE 2. These should live in a single csv that can be referenced once and filtered from with a header.

- [ ] Manual temperature flags (don't presently exist)
- [ ] Salinity flags (outputting to /tools?)
- [ ] Oxygen flags (few examples)
- [ ] **Bottle flags** don't exist in CTDCAL as is - should mark mistrips. None of the data get flagged, but skip using this data point for getting fit coefficients

**Comment by Klankers** [comment]
Discussed today. An issue we've routinely run into was that the manual salinity and oxygen reference flags were not being read in correctly. Not creating a duplicate issue, since it would be resolved by this (and our timeframes are the same).

**Comment by asmith75218** [comment]
Resolved in PR #106
