### ISSUE TITLE
Add support for SSSCC commenting

### ISSUE THREAD

**Issue by Klankers** [cchdo/ctdcal#87]
Support SSSCC commenting with leading `#`

This is helpful for adding/removing certain casts, turning them more into a "toggle" rather than an entry (which needs to be remembered between different files).

- Using open (as r or w)
- Pandas
- Numpy? [Numpy.genfromtxt()](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html)

During ARC01 we'll want to standardize what we use to read any/all CSV files from.

** Identified locations of CSV parsing ** 
process_ctd.py get_ssscc_list
- ssscc file
- `with: open`

rinko.py calibrate_oxy
- ssscc group files
- pandas `read_csv()`

odf_io.py _salt_loader
- salt files
- `csv.reader`

**Comment by asmith75218** [comment]
Addressed in PR #100.
