### ISSUE TITLE
Retain RINKO_T

### ISSUE THREAD

**Issue by Klankers** [cchdo/ctdcal#88]
The RINKO_T has not been included in CTDCAL processing, as the SBE3 has been used instead for the water parcel being sampled.

Data don't have to be written out or returned, but they should at least be available in the processing. Should happen before ARC01 for intercomparison purposes (especially with the RBR duet).

This happens in `convertFromSBEReader()` in convert.py. As with the rinko oxy column, current solution will depend on knowing what this parameter was named by the user in the xmlcon file.

**Comment by asmith75218** [comment]
Addressed in PR #101.
